/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef ENGINE_API
#define ENGINE_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern ENGINE_API FName ENGINE_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(AcceptPlayInfoProperty)
AUTOGENERATE_NAME(AddInteraction)
AUTOGENERATE_NAME(AllowClassRemoval)
AUTOGENERATE_NAME(AnimEnd)
AUTOGENERATE_NAME(Attach)
AUTOGENERATE_NAME(BaseChange)
AUTOGENERATE_NAME(BeginEvent)
AUTOGENERATE_NAME(BeginPlay)
AUTOGENERATE_NAME(BroadcastLocalizedMessage)
AUTOGENERATE_NAME(Bump)
AUTOGENERATE_NAME(ClientTrigger)
AUTOGENERATE_NAME(DemoPlaySound)
AUTOGENERATE_NAME(Destroyed)
AUTOGENERATE_NAME(Detach)
AUTOGENERATE_NAME(EncroachedBy)
AUTOGENERATE_NAME(EncroachingOn)
AUTOGENERATE_NAME(EndedRotation)
AUTOGENERATE_NAME(EndEvent)
AUTOGENERATE_NAME(Falling)
AUTOGENERATE_NAME(FellOutOfWorld)
AUTOGENERATE_NAME(FinishedInterpolation)
AUTOGENERATE_NAME(GainedChild)
AUTOGENERATE_NAME(GetDescriptionText)
AUTOGENERATE_NAME(GetSecurityLevel)
AUTOGENERATE_NAME(HitWall)
AUTOGENERATE_NAME(Initialized)
AUTOGENERATE_NAME(KApplyForce)
AUTOGENERATE_NAME(KilledBy)
AUTOGENERATE_NAME(KImpact)
AUTOGENERATE_NAME(KSkelConvulse)
AUTOGENERATE_NAME(KUpdateState)
AUTOGENERATE_NAME(KVelDropBelow)
AUTOGENERATE_NAME(Landed)
AUTOGENERATE_NAME(LIPSincAnimEnd)
AUTOGENERATE_NAME(LostChild)
AUTOGENERATE_NAME(NotifyLevelChange)
AUTOGENERATE_NAME(NotifyMusicChange)
AUTOGENERATE_NAME(OverrideDownload)
AUTOGENERATE_NAME(PhysicsVolumeChange)
AUTOGENERATE_NAME(PostBeginPlay)
AUTOGENERATE_NAME(PostLoadSavedGame)
AUTOGENERATE_NAME(PostNetBeginPlay)
AUTOGENERATE_NAME(PostNetReceive)
AUTOGENERATE_NAME(PostTeleport)
AUTOGENERATE_NAME(PostTouch)
AUTOGENERATE_NAME(PreBeginPlay)
AUTOGENERATE_NAME(PreSaveGame)
AUTOGENERATE_NAME(PreTeleport)
AUTOGENERATE_NAME(Process_KeyEvent)
AUTOGENERATE_NAME(Process_KeyType)
AUTOGENERATE_NAME(Process_Message)
AUTOGENERATE_NAME(Process_PostRender)
AUTOGENERATE_NAME(Process_PreRender)
AUTOGENERATE_NAME(Process_Tick)
AUTOGENERATE_NAME(RanInto)
AUTOGENERATE_NAME(RecoverFromBadStateCode)
AUTOGENERATE_NAME(RemoveInteraction)
AUTOGENERATE_NAME(RenderTexture)
AUTOGENERATE_NAME(ServerCallback)
AUTOGENERATE_NAME(SetFocusTo)
AUTOGENERATE_NAME(SetInitialState)
AUTOGENERATE_NAME(SpecialHandling)
AUTOGENERATE_NAME(TakeDamage)
AUTOGENERATE_NAME(Tick)
AUTOGENERATE_NAME(Timer)
AUTOGENERATE_NAME(TornOff)
AUTOGENERATE_NAME(Touch)
AUTOGENERATE_NAME(TravelPostAccept)
AUTOGENERATE_NAME(TravelPreAccept)
AUTOGENERATE_NAME(Trigger)
AUTOGENERATE_NAME(TriggerEvent)
AUTOGENERATE_NAME(UnTouch)
AUTOGENERATE_NAME(UnTrigger)
AUTOGENERATE_NAME(UsedBy)
AUTOGENERATE_NAME(ZoneChange)

#ifndef NAMES_ONLY

enum EFlagState
{
    FLAG_Home               =0,
    FLAG_HeldFriendly       =1,
    FLAG_HeldEnemy          =2,
    FLAG_Down               =3,
    FLAG_MAX                =4,
};
enum eKillZType
{
    KILLZ_None              =0,
    KILLZ_Lava              =1,
    KILLZ_Suicide           =2,
    KILLZ_MAX               =3,
};
enum EDoubleClickDir
{
    DCLICK_None             =0,
    DCLICK_Left             =1,
    DCLICK_Right            =2,
    DCLICK_Forward          =3,
    DCLICK_Back             =4,
    DCLICK_Active           =5,
    DCLICK_Done             =6,
    DCLICK_MAX              =7,
};
enum ETravelType
{
    TRAVEL_Absolute         =0,
    TRAVEL_Partial          =1,
    TRAVEL_Relative         =2,
    TRAVEL_MAX              =3,
};
enum EForceType
{
    FT_None                 =0,
    FT_DragAlong            =1,
    FT_Constant             =2,
    FT_MAX                  =3,
};
enum EMusicTransition
{
    MTRAN_None              =0,
    MTRAN_Instant           =1,
    MTRAN_Segue             =2,
    MTRAN_Fade              =3,
    MTRAN_FastFade          =4,
    MTRAN_SlowFade          =5,
    MTRAN_MAX               =6,
};
enum ESoundSlot
{
    SLOT_None               =0,
    SLOT_Misc               =1,
    SLOT_Pain               =2,
    SLOT_Interact           =3,
    SLOT_Ambient            =4,
    SLOT_Talk               =5,
    SLOT_Interface          =6,
    SLOT_MAX                =7,
};
enum ESoundOcclusion
{
    OCCLUSION_Default       =0,
    OCCLUSION_None          =1,
    OCCLUSION_BSP           =2,
    OCCLUSION_StaticMeshes  =3,
    OCCLUSION_MAX           =4,
};
enum ERenderStyle
{
    STY_None                =0,
    STY_Normal              =1,
    STY_Masked              =2,
    STY_Translucent         =3,
    STY_Modulated           =4,
    STY_Alpha               =5,
    STY_Additive            =6,
    STY_Subtractive         =7,
    STY_Particle            =8,
    STY_AlphaZ              =9,
    STY_MAX                 =10,
};
enum ESurfaceTypes
{
    EST_Default             =0,
    EST_Rock                =1,
    EST_Dirt                =2,
    EST_Metal               =3,
    EST_Wood                =4,
    EST_Plant               =5,
    EST_Flesh               =6,
    EST_Ice                 =7,
    EST_Snow                =8,
    EST_Water               =9,
    EST_Glass               =10,
    EST_Custom00            =11,
    EST_Custom01            =12,
    EST_Custom02            =13,
    EST_Custom03            =14,
    EST_Custom04            =15,
    EST_Custom05            =16,
    EST_Custom06            =17,
    EST_Custom07            =18,
    EST_Custom08            =19,
    EST_Custom09            =20,
    EST_Custom10            =21,
    EST_Custom11            =22,
    EST_Custom12            =23,
    EST_Custom13            =24,
    EST_Custom14            =25,
    EST_Custom15            =26,
    EST_Custom16            =27,
    EST_Custom17            =28,
    EST_Custom18            =29,
    EST_Custom19            =30,
    EST_Custom20            =31,
    EST_Custom21            =32,
    EST_Custom22            =33,
    EST_Custom23            =34,
    EST_Custom24            =35,
    EST_Custom25            =36,
    EST_Custom26            =37,
    EST_Custom27            =38,
    EST_Custom28            =39,
    EST_Custom29            =40,
    EST_Custom30            =41,
    EST_Custom31            =42,
    EST_MAX                 =43,
};
enum EUV2Mode
{
    UVM_MacroTexture        =0,
    UVM_LightMap            =1,
    UVM_Skin                =2,
    UVM_MAX                 =3,
};
enum ENetRole
{
    ROLE_None               =0,
    ROLE_DumbProxy          =1,
    ROLE_SimulatedProxy     =2,
    ROLE_AutonomousProxy    =3,
    ROLE_Authority          =4,
    ROLE_MAX                =5,
};
enum EPhysics
{
    PHYS_None               =0,
    PHYS_Walking            =1,
    PHYS_Falling            =2,
    PHYS_Swimming           =3,
    PHYS_Flying             =4,
    PHYS_Rotating           =5,
    PHYS_Projectile         =6,
    PHYS_Interpolating      =7,
    PHYS_MovingBrush        =8,
    PHYS_Spider             =9,
    PHYS_Trailer            =10,
    PHYS_Ladder             =11,
    PHYS_RootMotion         =12,
    PHYS_Karma              =13,
    PHYS_KarmaRagDoll       =14,
    PHYS_Hovering           =15,
    PHYS_CinMotion          =16,
    PHYS_MAX                =17,
};
enum EFilterState
{
    FS_Maybe                =0,
    FS_Yes                  =1,
    FS_No                   =2,
    FS_MAX                  =3,
};
enum EDrawType
{
    DT_None                 =0,
    DT_Sprite               =1,
    DT_Mesh                 =2,
    DT_Brush                =3,
    DT_RopeSprite           =4,
    DT_VerticalSprite       =5,
    DT_Terraform            =6,
    DT_SpriteAnimOnce       =7,
    DT_StaticMesh           =8,
    DT_DrawType             =9,
    DT_Particle             =10,
    DT_AntiPortal           =11,
    DT_FluidSurface         =12,
    DT_MAX                  =13,
};
enum ELightEffect
{
    LE_None                 =0,
    LE_TorchWaver           =1,
    LE_FireWaver            =2,
    LE_WateryShimmer        =3,
    LE_Searchlight          =4,
    LE_SlowWave             =5,
    LE_FastWave             =6,
    LE_CloudCast            =7,
    LE_StaticSpot           =8,
    LE_Shock                =9,
    LE_Disco                =10,
    LE_Warp                 =11,
    LE_Spotlight            =12,
    LE_NonIncidence         =13,
    LE_Shell                =14,
    LE_OmniBumpMap          =15,
    LE_Interference         =16,
    LE_Cylinder             =17,
    LE_Rotor                =18,
    LE_Negative             =19,
    LE_Sunlight             =20,
    LE_QuadraticNonIncidence=21,
    LE_MAX                  =22,
};
enum ELightType
{
    LT_None                 =0,
    LT_Steady               =1,
    LT_Pulse                =2,
    LT_Blink                =3,
    LT_Flicker              =4,
    LT_Strobe               =5,
    LT_BackdropLight        =6,
    LT_SubtlePulse          =7,
    LT_TexturePaletteOnce   =8,
    LT_TexturePaletteLoop   =9,
    LT_FadeOut              =10,
    LT_MAX                  =11,
};
#define UCONST_MINFLOORZ 0.7
#define UCONST_MAXSTEPHEIGHT 35.0

struct AActor_eventTriggerEvent_Parms
{
    FName EventName;
    class AActor* Other;
    class APawn* EventInstigator;
};
struct AActor_eventTravelPostAccept_Parms
{
};
struct AActor_eventTravelPreAccept_Parms
{
};
struct AActor_eventPostNetBeginPlay_Parms
{
};
struct AActor_eventSetInitialState_Parms
{
};
struct AActor_eventPostBeginPlay_Parms
{
};
struct AActor_eventBroadcastLocalizedMessage_Parms
{
    class UClass* MessageClass;
    INT Switch;
    class APlayerReplicationInfo* RelatedPRI_1;
    class APlayerReplicationInfo* RelatedPRI_2;
    class UObject* OptionalObject;
};
struct AActor_eventPreBeginPlay_Parms
{
};
struct AActor_eventRenderTexture_Parms
{
    class UScriptedTexture* Tex;
};
struct AActor_eventRecoverFromBadStateCode_Parms
{
};
struct AActor_eventBeginPlay_Parms
{
};
struct AActor_eventPostTeleport_Parms
{
    class ATeleporter* OutTeleporter;
};
struct AActor_eventPreTeleport_Parms
{
    class ATeleporter* InTeleporter;
    BITFIELD ReturnValue;
};
struct AActor_eventDemoPlaySound_Parms
{
    class USound* Sound;
    BYTE Slot;
    FLOAT Volume;
    BITFIELD bNoOverride;
    FLOAT Radius;
    FLOAT Pitch;
    BITFIELD Attenuate;
};
struct AActor_eventPostLoadSavedGame_Parms
{
};
struct AActor_eventPreSaveGame_Parms
{
};
struct AActor_eventTornOff_Parms
{
};
struct AActor_eventTakeDamage_Parms
{
    INT Damage;
    class APawn* EventInstigator;
    FVector HitLocation;
    FVector Momentum;
    class UClass* DamageType;
};
struct AActor_eventKilledBy_Parms
{
    class APawn* EventInstigator;
};
struct AActor_eventFellOutOfWorld_Parms
{
    BYTE KillType;
};
struct AActor_eventUsedBy_Parms
{
    class APawn* User;
};
struct AActor_eventEndedRotation_Parms
{
};
struct AActor_eventFinishedInterpolation_Parms
{
};
struct AActor_eventRanInto_Parms
{
    class AActor* Other;
};
struct AActor_eventEncroachedBy_Parms
{
    class AActor* Other;
};
struct AActor_eventEncroachingOn_Parms
{
    class AActor* Other;
    BITFIELD ReturnValue;
};
struct AActor_eventSpecialHandling_Parms
{
    class APawn* Other;
    class AActor* ReturnValue;
};
struct AActor_eventDetach_Parms
{
    class AActor* Other;
};
struct AActor_eventAttach_Parms
{
    class AActor* Other;
};
struct AActor_eventBaseChange_Parms
{
};
struct AActor_eventBump_Parms
{
    class AActor* Other;
};
struct AActor_eventUnTouch_Parms
{
    class AActor* Other;
};
struct AActor_eventPostTouch_Parms
{
    class AActor* Other;
};
struct AActor_eventTouch_Parms
{
    class AActor* Other;
};
struct AActor_eventPhysicsVolumeChange_Parms
{
    class APhysicsVolume* NewVolume;
};
struct AActor_eventZoneChange_Parms
{
    class AZoneInfo* NewZone;
};
struct AActor_eventLanded_Parms
{
    FVector HitNormal;
};
struct AActor_eventFalling_Parms
{
};
struct AActor_eventHitWall_Parms
{
    FVector HitNormal;
    class AActor* HitWall;
};
struct AActor_eventTimer_Parms
{
};
struct AActor_eventEndEvent_Parms
{
};
struct AActor_eventBeginEvent_Parms
{
};
struct AActor_eventUnTrigger_Parms
{
    class AActor* Other;
    class APawn* EventInstigator;
};
struct AActor_eventTrigger_Parms
{
    class AActor* Other;
    class APawn* EventInstigator;
};
struct AActor_eventClientTrigger_Parms
{
};
struct AActor_eventPostNetReceive_Parms
{
};
struct AActor_eventTick_Parms
{
    FLOAT DeltaTime;
};
struct AActor_eventLostChild_Parms
{
    class AActor* Other;
};
struct AActor_eventGainedChild_Parms
{
    class AActor* Other;
};
struct AActor_eventDestroyed_Parms
{
};
struct AActor_eventKUpdateState_Parms
{
    FKRigidBodyState NewState;
    BITFIELD ReturnValue;
};
struct AActor_eventKApplyForce_Parms
{
    FVector Force;
    FVector Torque;
};
struct AActor_eventKSkelConvulse_Parms
{
};
struct AActor_eventKVelDropBelow_Parms
{
};
struct AActor_eventKImpact_Parms
{
    class AActor* Other;
    FVector pos;
    FVector impactVel;
    FVector impactNorm;
};
struct AActor_eventAnimEnd_Parms
{
    INT Channel;
};
struct AActor_eventLIPSincAnimEnd_Parms
{
};
class ENGINE_API AActor : public UObject
{
public:
    BYTE LightType GCC_PACK(4);
    BYTE LightEffect;
    BYTE LightHue;
    BYTE LightSaturation;
    FLOAT LightBrightness GCC_PACK(4);
    FLOAT LightRadius;
    BYTE LightPeriod;
    BYTE LightPhase;
    BYTE LightCone;
    BYTE DrawType;
    BYTE StaticFilterState;
    class UStaticMesh* StaticMesh GCC_PACK(4);
    class AActor* Owner;
    class AActor* Base;
    FActorRenderDataPtr ActorRenderData;
    FLightRenderDataPtr LightRenderData;
    INT RenderRevision;
    TArrayNoInit<FBatchReference> StaticSectionBatches;
    FName ForcedVisibilityZoneTag;
    FLOAT CullDistance;
    BITFIELD bSpecialLit:1 GCC_PACK(4);
    BITFIELD bActorShadows:1;
    BITFIELD bCorona:1;
    BITFIELD bDirectionalCorona:1;
    BITFIELD bAttenByLife:1;
    BITFIELD bLightingVisibility:1;
    BITFIELD bUseDynamicLights:1;
    BITFIELD bLightChanged:1;
    BITFIELD bDramaticLighting:1;
    BITFIELD bStatic:1;
    BITFIELD bHidden:1;
    BITFIELD bNoDelete:1;
    BITFIELD bDeleteMe:1;
    BITFIELD bTicked:1;
    BITFIELD bDynamicLight:1;
    BITFIELD bTimerLoop:1;
    BITFIELD bOnlyOwnerSee:1;
    BITFIELD bHighDetail:1;
    BITFIELD bSuperHighDetail:1;
    BITFIELD bOnlyDrawIfAttached:1;
    BITFIELD bStasis:1;
    BITFIELD bTrailerAllowRotation:1;
    BITFIELD bTrailerSameRotation:1;
    BITFIELD bTrailerPrePivot:1;
    BITFIELD bWorldGeometry:1;
    BITFIELD bAcceptsProjectors:1;
    BITFIELD bOrientOnSlope:1;
    BITFIELD bOnlyAffectPawns:1;
    BITFIELD bDisableSorting:1;
    BITFIELD bIgnoreEncroachers:1;
    BITFIELD bShowOctreeNodes:1;
    BITFIELD bWasSNFiltered:1;
    BITFIELD bShouldStopKarma:1;
    BITFIELD bDetailAttachment:1;
    BITFIELD bNetTemporary:1;
    BITFIELD bOnlyRelevantToOwner:1;
    BITFIELD bNetDirty:1;
    BITFIELD bAlwaysRelevant:1;
    BITFIELD bReplicateInstigator:1;
    BITFIELD bReplicateMovement:1;
    BITFIELD bSkipActorPropertyReplication:1;
    BITFIELD bUpdateSimulatedPosition:1;
    BITFIELD bTearOff:1;
    BITFIELD bOnlyDirtyReplication:1;
    BITFIELD bReplicateAnimations:1;
    BITFIELD bNetInitialRotation:1;
    BITFIELD bCompressedPosition:1;
    BITFIELD bAlwaysZeroBoneOffset:1;
    BITFIELD bIgnoreVehicles:1;
    BITFIELD bDeferRendering:1;
    BITFIELD bBadStateCode:1;
    BYTE Physics GCC_PACK(4);
    BYTE RemoteRole;
    BYTE Role;
    INT NetTag GCC_PACK(4);
    FLOAT NetUpdateTime;
    FLOAT NetUpdateFrequency;
    FLOAT NetPriority;
    class APawn* Instigator;
    class USound* AmbientSound;
    FName AttachmentBone;
    class ALevelInfo* Level;
    class ULevel* XLevel;
    FLOAT LifeSpan;
    FPointRegion Region;
    FLOAT TimerRate;
    class UMaterial* OverlayMaterial;
    class UMesh* Mesh;
    FLOAT LastRenderTime;
    FName Tag;
    TArrayNoInit<INT> Leaves;
    FName Event;
    class AInventory* Inventory;
    FLOAT TimerCounter;
    class UMeshInstance* MeshInstance;
    FLOAT LODBias;
    FName InitialState;
    FName Group;
    TArrayNoInit<class AActor*> Touching;
    TArrayNoInit<PTRINT> OctreeNodes;
    FBox OctreeBox;
    FVector OctreeBoxCenter;
    FVector OctreeBoxRadii;
    class AActor* Deleted;
    FLOAT LatentFloat;
    INT CollisionTag;
    INT JoinedTag;
    class APhysicsVolume* PhysicsVolume;
    FVector Location;
    FRotator Rotation;
    FVector Velocity;
    FVector Acceleration;
    FVector CachedLocation;
    FRotator CachedRotation;
    FMatrix CachedLocalToWorld;
    FName AttachTag;
    TArrayNoInit<class AActor*> Attached;
    FVector RelativeLocation;
    FRotator RelativeRotation;
    FMatrix HardRelMatrix;
    TArrayNoInit<FProjectorRenderInfoPtr> Projectors;
    TArrayNoInit<FStaticMeshProjectorRenderInfoPtr> StaticMeshProjectors;
    class UMaterial* Texture;
    class UStaticMeshInstance* StaticMeshInstance;
    class UModel* Brush;
    FLOAT DrawScale;
    FVector DrawScale3D;
    FVector PrePivot;
    TArrayNoInit<class UMaterial*> Skins;
    class UMaterial* RepSkin;
    BYTE AmbientGlow;
    BYTE MaxLights;
    BYTE UV2Mode;
    class UConvexVolume* AntiPortal GCC_PACK(4);
    class UMaterial* UV2Texture;
    FLOAT ScaleGlow;
    BYTE SurfaceType;
    BYTE Style;
    BITFIELD bUnlit:1 GCC_PACK(4);
    BITFIELD bShadowCast:1;
    BITFIELD bStaticLighting:1;
    BITFIELD bUseLightingFromBase:1;
    BITFIELD bHurtEntry:1;
    BITFIELD bGameRelevant:1;
    BITFIELD bCollideWhenPlacing:1;
    BITFIELD bTravel:1;
    BITFIELD bMovable:1;
    BITFIELD bDestroyInPainVolume:1;
    BITFIELD bCanBeDamaged:1;
    BITFIELD bShouldBaseAtStartup:1;
    BITFIELD bPendingDelete:1;
    BITFIELD bAnimByOwner:1;
    BITFIELD bOwnerNoSee:1;
    BITFIELD bCanTeleport:1;
    BITFIELD bClientAnim:1;
    BITFIELD bDisturbFluidSurface:1;
    FLOAT FluidSurfaceShootStrengthMod GCC_PACK(4);
    BITFIELD bAlwaysTick:1 GCC_PACK(4);
    BITFIELD bFullVolume:1;
    BITFIELD bNotifyLocalPlayerTeamReceived:1;
    BITFIELD bHardAttach:1;
    BITFIELD bForceSkelUpdate:1;
    BITFIELD bClientAuthoritative:1;
    BYTE SoundVolume GCC_PACK(4);
    BYTE SoundPitch;
    BYTE SoundOcclusion;
    FLOAT SoundRadius GCC_PACK(4);
    FLOAT TransientSoundVolume;
    FLOAT TransientSoundRadius;
    FLOAT CollisionRadius;
    FLOAT CollisionHeight;
    BITFIELD bCollideActors:1 GCC_PACK(4);
    BITFIELD bCollideWorld:1;
    BITFIELD bBlockActors:1;
    BITFIELD bBlockPlayers:1;
    BITFIELD bBlockProjectiles:1;
    BITFIELD bProjTarget:1;
    BITFIELD bBlockZeroExtentTraces:1;
    BITFIELD bBlockNonZeroExtentTraces:1;
    BITFIELD bAutoAlignToTerrain:1;
    BITFIELD bUseCylinderCollision:1;
    BITFIELD bBlockKarma:1;
    BITFIELD bBlocksTeleport:1;
    BITFIELD bAlwaysFaceCamera:1;
    BITFIELD bNetNotify:1;
    BITFIELD bClientTrigger:1;
    BITFIELD bUseCollisionStaticMesh:1;
    BITFIELD bSmoothKarmaStateUpdates:1;
    BITFIELD bIgnoreOutOfWorld:1;
    BITFIELD bBounce:1;
    BITFIELD bFixedRotationDir:1;
    BITFIELD bRotateToDesired:1;
    BITFIELD bIgnoreTerminalVelocity:1;
    BITFIELD bOrientToVelocity:1;
    BITFIELD bInterpolating:1;
    BITFIELD bJustTeleported:1;
    FLOAT Mass GCC_PACK(4);
    FLOAT Buoyancy;
    FRotator RotationRate;
    FRotator DesiredRotation;
    class AActor* PendingTouch;
    FVector ColLocation;
    FName ExcludeTag[8];
    class UKarmaParamsCollision* KParams;
    INT KStepTag;
    FLOAT AccumKarmaAngleError;
    FAnimRep SimAnim;
    BYTE ForceType;
    FLOAT ForceRadius GCC_PACK(4);
    FLOAT ForceScale;
    FLOAT ForceNoise;
    BITFIELD bNetInitial:1 GCC_PACK(4);
    BITFIELD bNetOwner:1;
    BITFIELD bNetRelevant:1;
    BITFIELD bDemoRecording:1;
    BITFIELD bClientDemoRecording:1;
    BITFIELD bRepClientDemo:1;
    BITFIELD bClientDemoNetFunc:1;
    BITFIELD bDemoOwner:1;
    BITFIELD bNoRepMesh:1;
    BITFIELD bNotOnDedServer:1;
    BITFIELD bAlreadyPrecachedMaterials:1;
    BITFIELD bAlreadyPrecachedMeshes:1;
    BITFIELD bHiddenEd:1;
    BITFIELD bHiddenEdGroup:1;
    BITFIELD bDirectional:1;
    BITFIELD bSelected:1;
    BITFIELD bEdShouldSnap:1;
    BITFIELD bEdSnap:1;
    BITFIELD bTempEditor:1;
    BITFIELD bObsolete:1;
    BITFIELD bPathColliding:1;
    BITFIELD bPathTemp:1;
    BITFIELD bScriptInitialized:1;
    BITFIELD bLockLocation:1;
    BITFIELD bTraceWater:1;
    class UClass* MessageClass GCC_PACK(4);
    FLOAT OverlayTimer;
    FLOAT ClientOverlayTimer;
    FLOAT ClientOverlayCounter;
    class UMaterial* HighDetailOverlay;
    DECLARE_FUNCTION(execMultiply_ColorFloat);
    DECLARE_FUNCTION(execAdd_ColorColor);
    DECLARE_FUNCTION(execMultiply_FloatColor);
    DECLARE_FUNCTION(execSubtract_ColorColor);
    DECLARE_FUNCTION(execCollidingActors);
    DECLARE_FUNCTION(execVisibleCollidingActors);
    DECLARE_FUNCTION(execVisibleActors);
    DECLARE_FUNCTION(execRadiusActors);
    DECLARE_FUNCTION(execTraceActors);
    DECLARE_FUNCTION(execTouchingActors);
    DECLARE_FUNCTION(execBasedActors);
    DECLARE_FUNCTION(execChildActors);
    DECLARE_FUNCTION(execDynamicActors);
    DECLARE_FUNCTION(execAllActors);
    DECLARE_FUNCTION(execMoveCacheEntry);
    DECLARE_FUNCTION(execGetCacheEntry);
    DECLARE_FUNCTION(execGetAllIntDesc);
    DECLARE_FUNCTION(execGetAllInt);
    DECLARE_FUNCTION(execGetNextIntDesc);
    DECLARE_FUNCTION(execGetNextInt);
    DECLARE_FUNCTION(execGetURLMap);
    DECLARE_FUNCTION(execGetNextSkin);
    DECLARE_FUNCTION(execGetMapName);
    DECLARE_FUNCTION(execAddToPackageMap);
    DECLARE_FUNCTION(execResetStaticFilterState);
    DECLARE_FUNCTION(execSuggestFallVelocity);
    DECLARE_FUNCTION(execPlayerCanSeeMe);
    DECLARE_FUNCTION(execMakeNoise);
    DECLARE_FUNCTION(execForceFeedbackSupported);
    DECLARE_FUNCTION(execChangeBaseParamsFeedbackEffect);
    DECLARE_FUNCTION(execChangeSpringFeedbackEffect);
    DECLARE_FUNCTION(execStopFeedbackEffect);
    DECLARE_FUNCTION(execPlayFeedbackEffect);
    DECLARE_FUNCTION(execGetSoundDuration);
    DECLARE_FUNCTION(execDemoPlaySound);
    DECLARE_FUNCTION(execPlayOwnedSound);
    DECLARE_FUNCTION(execPlaySound);
    DECLARE_FUNCTION(execSetTimer);
    DECLARE_FUNCTION(execDestroy);
    DECLARE_FUNCTION(execSpawn);
    DECLARE_FUNCTION(execTraceThisActor);
    DECLARE_FUNCTION(execFastTrace);
    DECLARE_FUNCTION(execTrace);
    DECLARE_FUNCTION(execStopAllMusic);
    DECLARE_FUNCTION(execStopMusic);
    DECLARE_FUNCTION(execPlayMusic);
    DECLARE_FUNCTION(execPauseStream);
    DECLARE_FUNCTION(execAdjustVolume);
    DECLARE_FUNCTION(execSeekStream);
    DECLARE_FUNCTION(execStopStream);
    DECLARE_FUNCTION(execPlayStream);
    DECLARE_FUNCTION(execAllowMusicPlayback);
    DECLARE_FUNCTION(execUnClock);
    DECLARE_FUNCTION(execClock);
    DECLARE_FUNCTION(execKIsRagdollAvailable);
    DECLARE_FUNCTION(execKMakeRagdollAvailable);
    DECLARE_FUNCTION(execKRemoveAllBoneLifters);
    DECLARE_FUNCTION(execKRemoveLifterFromBone);
    DECLARE_FUNCTION(execKAddBoneLifter);
    DECLARE_FUNCTION(execKScaleJointLimits);
    DECLARE_FUNCTION(execKFreezeRagdoll);
    DECLARE_FUNCTION(execKGetSkelMass);
    DECLARE_FUNCTION(execKSetSkelVel);
    DECLARE_FUNCTION(execKEnableCollision);
    DECLARE_FUNCTION(execKDisableCollision);
    DECLARE_FUNCTION(execKGetActorGravScale);
    DECLARE_FUNCTION(execKSetActorGravScale);
    DECLARE_FUNCTION(execKSetBlockKarma);
    DECLARE_FUNCTION(execKSetStayUprightParams);
    DECLARE_FUNCTION(execKSetStayUpright);
    DECLARE_FUNCTION(execKAddAngularImpulse);
    DECLARE_FUNCTION(execKAddImpulse);
    DECLARE_FUNCTION(execKIsAwake);
    DECLARE_FUNCTION(execKWake);
    DECLARE_FUNCTION(execKGetImpactThreshold);
    DECLARE_FUNCTION(execKSetImpactThreshold);
    DECLARE_FUNCTION(execKGetCOMPosition);
    DECLARE_FUNCTION(execKGetCOMOffset);
    DECLARE_FUNCTION(execKSetCOMOffset);
    DECLARE_FUNCTION(execKGetRestitution);
    DECLARE_FUNCTION(execKSetRestitution);
    DECLARE_FUNCTION(execKGetFriction);
    DECLARE_FUNCTION(execKSetFriction);
    DECLARE_FUNCTION(execKGetDampingProps);
    DECLARE_FUNCTION(execKSetDampingProps);
    DECLARE_FUNCTION(execKGetInertiaTensor);
    DECLARE_FUNCTION(execKSetInertiaTensor);
    DECLARE_FUNCTION(execKGetMass);
    DECLARE_FUNCTION(execKSetMass);
    DECLARE_FUNCTION(execKRBVecFromVector);
    DECLARE_FUNCTION(execKRBVecToVector);
    DECLARE_FUNCTION(execKDrawRigidBodyState);
    DECLARE_FUNCTION(execKGetRigidBodyState);
    DECLARE_FUNCTION(execKGetRBQuaternion);
    DECLARE_FUNCTION(execKSetSimParams);
    DECLARE_FUNCTION(execKGetSimParams);
    DECLARE_FUNCTION(execOnlyAffectPawns);
    DECLARE_FUNCTION(execSetPhysics);
    DECLARE_FUNCTION(execFinishInterpolation);
    DECLARE_FUNCTION(execDebugUnclock);
    DECLARE_FUNCTION(execDebugClock);
    DECLARE_FUNCTION(execClearStayingDebugLines);
    DECLARE_FUNCTION(execDrawDebugSphere);
    DECLARE_FUNCTION(execDrawDebugCircle);
    DECLARE_FUNCTION(execDrawStayingDebugLine);
    DECLARE_FUNCTION(execDrawDebugLine);
    DECLARE_FUNCTION(execGetRenderBoundingSphere);
    DECLARE_FUNCTION(execGetUrlOption);
    DECLARE_FUNCTION(execUpdateURL);
    DECLARE_FUNCTION(execGetClosestBone);
    DECLARE_FUNCTION(execAnimIsInGroup);
    DECLARE_FUNCTION(execGetAnimParams);
    DECLARE_FUNCTION(execSetBoneRotation);
    DECLARE_FUNCTION(execSetBoneLocation);
    DECLARE_FUNCTION(execSetBoneDirection);
    DECLARE_FUNCTION(execSetBoneScale);
    DECLARE_FUNCTION(execLockRootMotion);
    DECLARE_FUNCTION(execDetachFromBone);
    DECLARE_FUNCTION(execAttachToBone);
    DECLARE_FUNCTION(execGetRootRotationDelta);
    DECLARE_FUNCTION(execGetRootLocationDelta);
    DECLARE_FUNCTION(execGetRootRotation);
    DECLARE_FUNCTION(execGetRootLocation);
    DECLARE_FUNCTION(execGetBoneRotation);
    DECLARE_FUNCTION(execGetBoneCoords);
    DECLARE_FUNCTION(execAnimBlendToAlpha);
    DECLARE_FUNCTION(execAnimBlendParams);
    DECLARE_FUNCTION(execBoneRefresh);
    DECLARE_FUNCTION(execLinkMesh);
    DECLARE_FUNCTION(execLinkSkelAnim);
    DECLARE_FUNCTION(execGetNotifyChannel);
    DECLARE_FUNCTION(execEnableChannelNotify);
    DECLARE_FUNCTION(execCurrentLIPSincAnim);
    DECLARE_FUNCTION(execIsPlayingLIPSincAnim);
    DECLARE_FUNCTION(execHasLIPSincAnim);
    DECLARE_FUNCTION(execStopLIPSincAnim);
    DECLARE_FUNCTION(execPlayLIPSincAnim);
    DECLARE_FUNCTION(execAnimStopLooping);
    DECLARE_FUNCTION(execIsTweening);
    DECLARE_FUNCTION(execSetAnimFrame);
    DECLARE_FUNCTION(execFreezeAnimAt);
    DECLARE_FUNCTION(execStopAnimating);
    DECLARE_FUNCTION(execHasAnim);
    DECLARE_FUNCTION(execFinishAnim);
    DECLARE_FUNCTION(execIsAnimating);
    DECLARE_FUNCTION(execTweenAnim);
    DECLARE_FUNCTION(execLoopAnim);
    DECLARE_FUNCTION(execPlayAnim);
    DECLARE_FUNCTION(execGetMeshName);
    DECLARE_FUNCTION(execIsJoinedTo);
    DECLARE_FUNCTION(execSetOwner);
    DECLARE_FUNCTION(execSetBase);
    DECLARE_FUNCTION(execAutonomousPhysics);
    DECLARE_FUNCTION(execMoveSmooth);
    DECLARE_FUNCTION(execSetRelativeLocation);
    DECLARE_FUNCTION(execSetRelativeRotation);
    DECLARE_FUNCTION(execSetRotation);
    DECLARE_FUNCTION(execSetLocation);
    DECLARE_FUNCTION(execMove);
    DECLARE_FUNCTION(execSetDrawType);
    DECLARE_FUNCTION(execSetStaticMesh);
    DECLARE_FUNCTION(execSetDrawScale3D);
    DECLARE_FUNCTION(execSetDrawScale);
    DECLARE_FUNCTION(execSetCollisionSize);
    DECLARE_FUNCTION(execSetCollision);
    DECLARE_FUNCTION(execSleep);
    DECLARE_FUNCTION(execShouldBeHidden);
    DECLARE_FUNCTION(execError);
    DECLARE_FUNCTION(execTextToSpeech);
    DECLARE_FUNCTION(execCopyObjectToClipboard);
    DECLARE_FUNCTION(execConsoleCommand);
    void eventTriggerEvent(FName EventName, class AActor* Other, class APawn* EventInstigator)
    {
        AActor_eventTriggerEvent_Parms Parms;
        Parms.EventName=EventName;
        Parms.Other=Other;
        Parms.EventInstigator=EventInstigator;
        ProcessEvent(FindFunctionChecked(ENGINE_TriggerEvent),&Parms);
    }
    void eventTravelPostAccept()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_TravelPostAccept),NULL);
    }
    void eventTravelPreAccept()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_TravelPreAccept),NULL);
    }
    void eventPostNetBeginPlay()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_PostNetBeginPlay),NULL);
    }
    void eventSetInitialState()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_SetInitialState),NULL);
    }
    void eventPostBeginPlay()
    {
        if(IsProbing(NAME_PostBeginPlay)) {
        ProcessEvent(FindFunctionChecked(ENGINE_PostBeginPlay),NULL);
        }
    }
    void eventBroadcastLocalizedMessage(class UClass* MessageClass, INT Switch, class APlayerReplicationInfo* RelatedPRI_1, class APlayerReplicationInfo* RelatedPRI_2, class UObject* OptionalObject)
    {
        AActor_eventBroadcastLocalizedMessage_Parms Parms;
        Parms.MessageClass=MessageClass;
        Parms.Switch=Switch;
        Parms.RelatedPRI_1=RelatedPRI_1;
        Parms.RelatedPRI_2=RelatedPRI_2;
        Parms.OptionalObject=OptionalObject;
        ProcessEvent(FindFunctionChecked(ENGINE_BroadcastLocalizedMessage),&Parms);
    }
    void eventPreBeginPlay()
    {
        if(IsProbing(NAME_PreBeginPlay)) {
        ProcessEvent(FindFunctionChecked(ENGINE_PreBeginPlay),NULL);
        }
    }
    void eventRenderTexture(class UScriptedTexture* Tex)
    {
        AActor_eventRenderTexture_Parms Parms;
        Parms.Tex=Tex;
        ProcessEvent(FindFunctionChecked(ENGINE_RenderTexture),&Parms);
    }
    void eventRecoverFromBadStateCode()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_RecoverFromBadStateCode),NULL);
    }
    void eventBeginPlay()
    {
        if(IsProbing(NAME_BeginPlay)) {
        ProcessEvent(FindFunctionChecked(ENGINE_BeginPlay),NULL);
        }
    }
    void eventPostTeleport(class ATeleporter* OutTeleporter)
    {
        AActor_eventPostTeleport_Parms Parms;
        Parms.OutTeleporter=OutTeleporter;
        ProcessEvent(FindFunctionChecked(ENGINE_PostTeleport),&Parms);
    }
    BITFIELD eventPreTeleport(class ATeleporter* InTeleporter)
    {
        AActor_eventPreTeleport_Parms Parms;
        Parms.ReturnValue=0;
        Parms.InTeleporter=InTeleporter;
        ProcessEvent(FindFunctionChecked(ENGINE_PreTeleport),&Parms);
        return Parms.ReturnValue;
    }
    void eventDemoPlaySound(class USound* Sound, BYTE Slot, FLOAT Volume, BITFIELD bNoOverride, FLOAT Radius, FLOAT Pitch, BITFIELD Attenuate)
    {
        AActor_eventDemoPlaySound_Parms Parms;
        Parms.Sound=Sound;
        Parms.Slot=Slot;
        Parms.Volume=Volume;
        Parms.bNoOverride=((bNoOverride) ? FIRST_BITFIELD : 0);
        Parms.Radius=Radius;
        Parms.Pitch=Pitch;
        Parms.Attenuate=((Attenuate) ? FIRST_BITFIELD : 0);
        ProcessEvent(FindFunctionChecked(ENGINE_DemoPlaySound),&Parms);
    }
    void eventPostLoadSavedGame()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_PostLoadSavedGame),NULL);
    }
    void eventPreSaveGame()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_PreSaveGame),NULL);
    }
    void eventTornOff()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_TornOff),NULL);
    }
    void eventTakeDamage(INT Damage, class APawn* EventInstigator, FVector HitLocation, FVector Momentum, class UClass* DamageType)
    {
        AActor_eventTakeDamage_Parms Parms;
        Parms.Damage=Damage;
        Parms.EventInstigator=EventInstigator;
        Parms.HitLocation=HitLocation;
        Parms.Momentum=Momentum;
        Parms.DamageType=DamageType;
        ProcessEvent(FindFunctionChecked(ENGINE_TakeDamage),&Parms);
    }
    void eventKilledBy(class APawn* EventInstigator)
    {
        AActor_eventKilledBy_Parms Parms;
        Parms.EventInstigator=EventInstigator;
        ProcessEvent(FindFunctionChecked(ENGINE_KilledBy),&Parms);
    }
    void eventFellOutOfWorld(BYTE KillType)
    {
        AActor_eventFellOutOfWorld_Parms Parms;
        Parms.KillType=KillType;
        ProcessEvent(FindFunctionChecked(ENGINE_FellOutOfWorld),&Parms);
    }
    void eventUsedBy(class APawn* User)
    {
        AActor_eventUsedBy_Parms Parms;
        Parms.User=User;
        ProcessEvent(FindFunctionChecked(ENGINE_UsedBy),&Parms);
    }
    void eventEndedRotation()
    {
        if(IsProbing(NAME_EndedRotation)) {
        ProcessEvent(FindFunctionChecked(ENGINE_EndedRotation),NULL);
        }
    }
    void eventFinishedInterpolation()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_FinishedInterpolation),NULL);
    }
    void eventRanInto(class AActor* Other)
    {
        AActor_eventRanInto_Parms Parms;
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_RanInto),&Parms);
    }
    void eventEncroachedBy(class AActor* Other)
    {
        AActor_eventEncroachedBy_Parms Parms;
        if(IsProbing(NAME_EncroachedBy)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_EncroachedBy),&Parms);
        }
    }
    BITFIELD eventEncroachingOn(class AActor* Other)
    {
        AActor_eventEncroachingOn_Parms Parms;
        Parms.ReturnValue=0;
        if(IsProbing(NAME_EncroachingOn)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_EncroachingOn),&Parms);
        }
        return Parms.ReturnValue;
    }
    class AActor* eventSpecialHandling(class APawn* Other)
    {
        AActor_eventSpecialHandling_Parms Parms;
        Parms.ReturnValue=0;
        if(IsProbing(NAME_SpecialHandling)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_SpecialHandling),&Parms);
        }
        return Parms.ReturnValue;
    }
    void eventDetach(class AActor* Other)
    {
        AActor_eventDetach_Parms Parms;
        if(IsProbing(NAME_Detach)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_Detach),&Parms);
        }
    }
    void eventAttach(class AActor* Other)
    {
        AActor_eventAttach_Parms Parms;
        if(IsProbing(NAME_Attach)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_Attach),&Parms);
        }
    }
    void eventBaseChange()
    {
        if(IsProbing(NAME_BaseChange)) {
        ProcessEvent(FindFunctionChecked(ENGINE_BaseChange),NULL);
        }
    }
    void eventBump(class AActor* Other)
    {
        AActor_eventBump_Parms Parms;
        if(IsProbing(NAME_Bump)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_Bump),&Parms);
        }
    }
    void eventUnTouch(class AActor* Other)
    {
        AActor_eventUnTouch_Parms Parms;
        if(IsProbing(NAME_UnTouch)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_UnTouch),&Parms);
        }
    }
    void eventPostTouch(class AActor* Other)
    {
        AActor_eventPostTouch_Parms Parms;
        if(IsProbing(NAME_PostTouch)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_PostTouch),&Parms);
        }
    }
    void eventTouch(class AActor* Other)
    {
        AActor_eventTouch_Parms Parms;
        if(IsProbing(NAME_Touch)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_Touch),&Parms);
        }
    }
    void eventPhysicsVolumeChange(class APhysicsVolume* NewVolume)
    {
        AActor_eventPhysicsVolumeChange_Parms Parms;
        if(IsProbing(NAME_PhysicsVolumeChange)) {
        Parms.NewVolume=NewVolume;
        ProcessEvent(FindFunctionChecked(ENGINE_PhysicsVolumeChange),&Parms);
        }
    }
    void eventZoneChange(class AZoneInfo* NewZone)
    {
        AActor_eventZoneChange_Parms Parms;
        if(IsProbing(NAME_ZoneChange)) {
        Parms.NewZone=NewZone;
        ProcessEvent(FindFunctionChecked(ENGINE_ZoneChange),&Parms);
        }
    }
    void eventLanded(FVector HitNormal)
    {
        AActor_eventLanded_Parms Parms;
        if(IsProbing(NAME_Landed)) {
        Parms.HitNormal=HitNormal;
        ProcessEvent(FindFunctionChecked(ENGINE_Landed),&Parms);
        }
    }
    void eventFalling()
    {
        if(IsProbing(NAME_Falling)) {
        ProcessEvent(FindFunctionChecked(ENGINE_Falling),NULL);
        }
    }
    void eventHitWall(FVector HitNormal, class AActor* HitWall)
    {
        AActor_eventHitWall_Parms Parms;
        if(IsProbing(NAME_HitWall)) {
        Parms.HitNormal=HitNormal;
        Parms.HitWall=HitWall;
        ProcessEvent(FindFunctionChecked(ENGINE_HitWall),&Parms);
        }
    }
    void eventTimer()
    {
        if(IsProbing(NAME_Timer)) {
        ProcessEvent(FindFunctionChecked(ENGINE_Timer),NULL);
        }
    }
    void eventEndEvent()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_EndEvent),NULL);
    }
    void eventBeginEvent()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_BeginEvent),NULL);
    }
    void eventUnTrigger(class AActor* Other, class APawn* EventInstigator)
    {
        AActor_eventUnTrigger_Parms Parms;
        if(IsProbing(NAME_UnTrigger)) {
        Parms.Other=Other;
        Parms.EventInstigator=EventInstigator;
        ProcessEvent(FindFunctionChecked(ENGINE_UnTrigger),&Parms);
        }
    }
    void eventTrigger(class AActor* Other, class APawn* EventInstigator)
    {
        AActor_eventTrigger_Parms Parms;
        if(IsProbing(NAME_Trigger)) {
        Parms.Other=Other;
        Parms.EventInstigator=EventInstigator;
        ProcessEvent(FindFunctionChecked(ENGINE_Trigger),&Parms);
        }
    }
    void eventClientTrigger()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_ClientTrigger),NULL);
    }
    void eventPostNetReceive()
    {
        if(IsProbing(NAME_PostNetReceive)) {
        ProcessEvent(FindFunctionChecked(ENGINE_PostNetReceive),NULL);
        }
    }
    void eventTick(FLOAT DeltaTime)
    {
        AActor_eventTick_Parms Parms;
        if(IsProbing(NAME_Tick)) {
        Parms.DeltaTime=DeltaTime;
        ProcessEvent(FindFunctionChecked(ENGINE_Tick),&Parms);
        }
    }
    void eventLostChild(class AActor* Other)
    {
        AActor_eventLostChild_Parms Parms;
        if(IsProbing(NAME_LostChild)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_LostChild),&Parms);
        }
    }
    void eventGainedChild(class AActor* Other)
    {
        AActor_eventGainedChild_Parms Parms;
        if(IsProbing(NAME_GainedChild)) {
        Parms.Other=Other;
        ProcessEvent(FindFunctionChecked(ENGINE_GainedChild),&Parms);
        }
    }
    void eventDestroyed()
    {
        if(IsProbing(NAME_Destroyed)) {
        ProcessEvent(FindFunctionChecked(ENGINE_Destroyed),NULL);
        }
    }
    BITFIELD eventKUpdateState(FKRigidBodyState& NewState)
    {
        AActor_eventKUpdateState_Parms Parms;
        Parms.ReturnValue=0;
        Parms.NewState=NewState;
        ProcessEvent(FindFunctionChecked(ENGINE_KUpdateState),&Parms);
        NewState=Parms.NewState;
        return Parms.ReturnValue;
    }
    void eventKApplyForce(FVector& Force, FVector& Torque)
    {
        AActor_eventKApplyForce_Parms Parms;
        Parms.Force=Force;
        Parms.Torque=Torque;
        ProcessEvent(FindFunctionChecked(ENGINE_KApplyForce),&Parms);
        Force=Parms.Force;
        Torque=Parms.Torque;
    }
    void eventKSkelConvulse()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_KSkelConvulse),NULL);
    }
    void eventKVelDropBelow()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_KVelDropBelow),NULL);
    }
    void eventKImpact(class AActor* Other, FVector pos, FVector impactVel, FVector impactNorm)
    {
        AActor_eventKImpact_Parms Parms;
        Parms.Other=Other;
        Parms.pos=pos;
        Parms.impactVel=impactVel;
        Parms.impactNorm=impactNorm;
        ProcessEvent(FindFunctionChecked(ENGINE_KImpact),&Parms);
    }
    void eventAnimEnd(INT Channel)
    {
        AActor_eventAnimEnd_Parms Parms;
        if(IsProbing(NAME_AnimEnd)) {
        Parms.Channel=Channel;
        ProcessEvent(FindFunctionChecked(ENGINE_AnimEnd),&Parms);
        }
    }
    void eventLIPSincAnimEnd()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_LIPSincAnimEnd),NULL);
    }
    DECLARE_CLASS(AActor,UObject,0|CLASS_NativeReplication,Engine)
    #include "AActor.h"
};


struct AInfo_eventGetDescriptionText_Parms
{
    FString PropName;
    FString ReturnValue;
};
struct AInfo_eventGetSecurityLevel_Parms
{
    FString PropName;
    BYTE ReturnValue;
};
struct AInfo_eventAllowClassRemoval_Parms
{
    BITFIELD ReturnValue;
};
struct AInfo_eventAcceptPlayInfoProperty_Parms
{
    FString PropertyName;
    BITFIELD ReturnValue;
};
class ENGINE_API AInfo : public AActor
{
public:
    FStringNoInit RulesGroup GCC_PACK(4);
    FStringNoInit GameGroup;
    FStringNoInit ServerGroup;
    FStringNoInit ChatGroup;
    FStringNoInit BotsGroup;
    FStringNoInit MapVoteGroup;
    FStringNoInit KickVoteGroup;
    FString eventGetDescriptionText(const FString& PropName)
    {
        AInfo_eventGetDescriptionText_Parms Parms;
        Parms.PropName=PropName;
        ProcessEvent(FindFunctionChecked(ENGINE_GetDescriptionText),&Parms);
        return Parms.ReturnValue;
    }
    BYTE eventGetSecurityLevel(const FString& PropName)
    {
        AInfo_eventGetSecurityLevel_Parms Parms;
        Parms.ReturnValue=0;
        Parms.PropName=PropName;
        ProcessEvent(FindFunctionChecked(ENGINE_GetSecurityLevel),&Parms);
        return Parms.ReturnValue;
    }
    BITFIELD eventAllowClassRemoval()
    {
        AInfo_eventAllowClassRemoval_Parms Parms;
        Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(ENGINE_AllowClassRemoval),&Parms);
        return Parms.ReturnValue;
    }
    BITFIELD eventAcceptPlayInfoProperty(const FString& PropertyName)
    {
        AInfo_eventAcceptPlayInfoProperty_Parms Parms;
        Parms.ReturnValue=0;
        Parms.PropertyName=PropertyName;
        ProcessEvent(FindFunctionChecked(ENGINE_AcceptPlayInfoProperty),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(AInfo,AActor,0,Engine)
    NO_DEFAULT_CONSTRUCTOR(AInfo)
};


struct AMutator_eventOverrideDownload_Parms
{
    FString PlayerIP;
    FString PlayerID;
    FString PlayerURL;
    FString RedirectURL;
    BITFIELD ReturnValue;
};
class ENGINE_API AMutator : public AInfo
{
public:
    class AMutator* NextMutator GCC_PACK(4);
    class UClass* DefaultWeapon;
    FStringNoInit DefaultWeaponName;
    BITFIELD bUserAdded:1 GCC_PACK(4);
    BITFIELD bAddToServerPackages:1;
    FStringNoInit IconMaterialName GCC_PACK(4);
    FStringNoInit ConfigMenuClassName;
    FStringNoInit GroupName;
    FStringNoInit FriendlyName;
    FStringNoInit Description;
    BITFIELD eventOverrideDownload(const FString& PlayerIP, const FString& PlayerID, const FString& PlayerURL, FString& RedirectURL)
    {
        AMutator_eventOverrideDownload_Parms Parms;
        Parms.ReturnValue=0;
        Parms.PlayerIP=PlayerIP;
        Parms.PlayerID=PlayerID;
        Parms.PlayerURL=PlayerURL;
        Parms.RedirectURL=RedirectURL;
        ProcessEvent(FindFunctionChecked(ENGINE_OverrideDownload),&Parms);
        RedirectURL=Parms.RedirectURL;
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(AMutator,AInfo,0,Engine)
    NO_DEFAULT_CONSTRUCTOR(AMutator)
};

struct ASecurity_eventServerCallback_Parms
{
    INT SecType;
    FString Data;
};
class ENGINE_API ASecurity : public AInfo
{
public:
    INT LastType GCC_PACK(4);
    FStringNoInit LastParams[2];
    DECLARE_FUNCTION(execLocalPerform);
    DECLARE_FUNCTION(execNativePerform);
    void eventServerCallback(INT SecType, const FString& Data)
    {
        ASecurity_eventServerCallback_Parms Parms;
        Parms.SecType=SecType;
        Parms.Data=Data;
        ProcessEvent(FindFunctionChecked(ENGINE_ServerCallback),&Parms);
    }
    DECLARE_CLASS(ASecurity,AInfo,0,Engine)
    ASecurity();
};

enum ECsgOper
{
    CSG_Active              =0,
    CSG_Add                 =1,
    CSG_Subtract            =2,
    CSG_Intersect           =3,
    CSG_Deintersect         =4,
    CSG_MAX                 =5,
};

class ENGINE_API ABrush : public AActor
{
public:
    BYTE CsgOper GCC_PACK(4);
    class UObject* UnusedLightMesh GCC_PACK(4);
    FVector PostPivot;
    FScale MainScale;
    FScale PostScale;
    FScale TempScale;
    FColor BrushColor;
    INT PolyFlags;
    BITFIELD bColored:1 GCC_PACK(4);
    DECLARE_CLASS(ABrush,AActor,0,Engine)
    #include "ABrush.h"
};


class ENGINE_API AVolume : public ABrush
{
public:
    class AActor* AssociatedActor GCC_PACK(4);
    FName AssociatedActorTag;
    INT LocationPriority;
    FStringNoInit LocationName;
    class ADecorationList* DecoList;
    DECLARE_FUNCTION(execEncompasses);
    DECLARE_CLASS(AVolume,ABrush,0,Engine)
    #include "AVolume.h"
};


class ENGINE_API ABlockingVolume : public AVolume
{
public:
    BITFIELD bClampFluid:1 GCC_PACK(4);
    BITFIELD bClassBlocker:1;
    TArrayNoInit<class UClass*> BlockedClasses GCC_PACK(4);
    DECLARE_CLASS(ABlockingVolume,AVolume,0,Engine)
    virtual UBOOL ShouldTrace(AActor *SourceActor, DWORD TraceFlags);
};

enum EStreamFinishReason
{
    STREAMFINISH_EOF        =0,
    STREAMFINISH_Error      =1,
    STREAMFINISH_MAX        =2,
};
enum EInputKey
{
    IK_None                 =0,
    IK_LeftMouse            =1,
    IK_RightMouse           =2,
    IK_Cancel               =3,
    IK_MiddleMouse          =4,
    IK_Unknown05            =5,
    IK_Unknown06            =6,
    IK_Unknown07            =7,
    IK_Backspace            =8,
    IK_Tab                  =9,
    IK_Unknown0A            =10,
    IK_Unknown0B            =11,
    IK_Unknown0C            =12,
    IK_Enter                =13,
    IK_Unknown0E            =14,
    IK_Unknown0F            =15,
    IK_Shift                =16,
    IK_Ctrl                 =17,
    IK_Alt                  =18,
    IK_Pause                =19,
    IK_CapsLock             =20,
    IK_Unknown15            =21,
    IK_Unknown16            =22,
    IK_Unknown17            =23,
    IK_Unknown18            =24,
    IK_Unknown19            =25,
    IK_Unknown1A            =26,
    IK_Escape               =27,
    IK_Unknown1C            =28,
    IK_Unknown1D            =29,
    IK_Unknown1E            =30,
    IK_Unknown1F            =31,
    IK_Space                =32,
    IK_PageUp               =33,
    IK_PageDown             =34,
    IK_End                  =35,
    IK_Home                 =36,
    IK_Left                 =37,
    IK_Up                   =38,
    IK_Right                =39,
    IK_Down                 =40,
    IK_Select               =41,
    IK_Print                =42,
    IK_Execute              =43,
    IK_PrintScrn            =44,
    IK_Insert               =45,
    IK_Delete               =46,
    IK_Help                 =47,
    IK_0                    =48,
    IK_1                    =49,
    IK_2                    =50,
    IK_3                    =51,
    IK_4                    =52,
    IK_5                    =53,
    IK_6                    =54,
    IK_7                    =55,
    IK_8                    =56,
    IK_9                    =57,
    IK_Unknown3A            =58,
    IK_Unknown3B            =59,
    IK_Unknown3C            =60,
    IK_Unknown3D            =61,
    IK_Unknown3E            =62,
    IK_Unknown3F            =63,
    IK_Unknown40            =64,
    IK_A                    =65,
    IK_B                    =66,
    IK_C                    =67,
    IK_D                    =68,
    IK_E                    =69,
    IK_F                    =70,
    IK_G                    =71,
    IK_H                    =72,
    IK_I                    =73,
    IK_J                    =74,
    IK_K                    =75,
    IK_L                    =76,
    IK_M                    =77,
    IK_N                    =78,
    IK_O                    =79,
    IK_P                    =80,
    IK_Q                    =81,
    IK_R                    =82,
    IK_S                    =83,
    IK_T                    =84,
    IK_U                    =85,
    IK_V                    =86,
    IK_W                    =87,
    IK_X                    =88,
    IK_Y                    =89,
    IK_Z                    =90,
    IK_Unknown5B            =91,
    IK_Unknown5C            =92,
    IK_Unknown5D            =93,
    IK_Unknown5E            =94,
    IK_Unknown5F            =95,
    IK_NumPad0              =96,
    IK_NumPad1              =97,
    IK_NumPad2              =98,
    IK_NumPad3              =99,
    IK_NumPad4              =100,
    IK_NumPad5              =101,
    IK_NumPad6              =102,
    IK_NumPad7              =103,
    IK_NumPad8              =104,
    IK_NumPad9              =105,
    IK_GreyStar             =106,
    IK_GreyPlus             =107,
    IK_Separator            =108,
    IK_GreyMinus            =109,
    IK_NumPadPeriod         =110,
    IK_GreySlash            =111,
    IK_F1                   =112,
    IK_F2                   =113,
    IK_F3                   =114,
    IK_F4                   =115,
    IK_F5                   =116,
    IK_F6                   =117,
    IK_F7                   =118,
    IK_F8                   =119,
    IK_F9                   =120,
    IK_F10                  =121,
    IK_F11                  =122,
    IK_F12                  =123,
    IK_F13                  =124,
    IK_F14                  =125,
    IK_F15                  =126,
    IK_F16                  =127,
    IK_F17                  =128,
    IK_F18                  =129,
    IK_F19                  =130,
    IK_F20                  =131,
    IK_F21                  =132,
    IK_F22                  =133,
    IK_F23                  =134,
    IK_F24                  =135,
    IK_Unknown88            =136,
    IK_Unknown89            =137,
    IK_Unknown8A            =138,
    IK_Unknown8B            =139,
    IK_Unknown8C            =140,
    IK_Unknown8D            =141,
    IK_Unknown8E            =142,
    IK_Unknown8F            =143,
    IK_NumLock              =144,
    IK_ScrollLock           =145,
    IK_Unknown92            =146,
    IK_Unknown93            =147,
    IK_Unknown94            =148,
    IK_Unknown95            =149,
    IK_Unknown96            =150,
    IK_Unknown97            =151,
    IK_Unknown98            =152,
    IK_Unknown99            =153,
    IK_Unknown9A            =154,
    IK_Unknown9B            =155,
    IK_Unknown9C            =156,
    IK_Unknown9D            =157,
    IK_Unknown9E            =158,
    IK_Unknown9F            =159,
    IK_LShift               =160,
    IK_RShift               =161,
    IK_LControl             =162,
    IK_RControl             =163,
    IK_UnknownA4            =164,
    IK_UnknownA5            =165,
    IK_UnknownA6            =166,
    IK_UnknownA7            =167,
    IK_UnknownA8            =168,
    IK_UnknownA9            =169,
    IK_UnknownAA            =170,
    IK_UnknownAB            =171,
    IK_UnknownAC            =172,
    IK_UnknownAD            =173,
    IK_UnknownAE            =174,
    IK_UnknownAF            =175,
    IK_UnknownB0            =176,
    IK_UnknownB1            =177,
    IK_UnknownB2            =178,
    IK_UnknownB3            =179,
    IK_UnknownB4            =180,
    IK_UnknownB5            =181,
    IK_UnknownB6            =182,
    IK_UnknownB7            =183,
    IK_UnknownB8            =184,
    IK_Unicode              =185,
    IK_Semicolon            =186,
    IK_Equals               =187,
    IK_Comma                =188,
    IK_Minus                =189,
    IK_Period               =190,
    IK_Slash                =191,
    IK_Tilde                =192,
    IK_Mouse4               =193,
    IK_Mouse5               =194,
    IK_Mouse6               =195,
    IK_Mouse7               =196,
    IK_Mouse8               =197,
    IK_UnknownC6            =198,
    IK_UnknownC7            =199,
    IK_Joy1                 =200,
    IK_Joy2                 =201,
    IK_Joy3                 =202,
    IK_Joy4                 =203,
    IK_Joy5                 =204,
    IK_Joy6                 =205,
    IK_Joy7                 =206,
    IK_Joy8                 =207,
    IK_Joy9                 =208,
    IK_Joy10                =209,
    IK_Joy11                =210,
    IK_Joy12                =211,
    IK_Joy13                =212,
    IK_Joy14                =213,
    IK_Joy15                =214,
    IK_Joy16                =215,
    IK_UnknownD8            =216,
    IK_UnknownD9            =217,
    IK_UnknownDA            =218,
    IK_LeftBracket          =219,
    IK_Backslash            =220,
    IK_RightBracket         =221,
    IK_SingleQuote          =222,
    IK_UnknownDF            =223,
    IK_UnknownE0            =224,
    IK_UnknownE1            =225,
    IK_UnknownE2            =226,
    IK_UnknownE3            =227,
    IK_MouseX               =228,
    IK_MouseY               =229,
    IK_MouseZ               =230,
    IK_MouseW               =231,
    IK_JoyU                 =232,
    IK_JoyV                 =233,
    IK_JoySlider1           =234,
    IK_JoySlider2           =235,
    IK_MouseWheelUp         =236,
    IK_MouseWheelDown       =237,
    IK_Unknown10E           =238,
    UK_Unknown10F           =239,
    IK_JoyX                 =240,
    IK_JoyY                 =241,
    IK_JoyZ                 =242,
    IK_JoyR                 =243,
    IK_UnknownF4            =244,
    IK_UnknownF5            =245,
    IK_Attn                 =246,
    IK_CrSel                =247,
    IK_ExSel                =248,
    IK_ErEof                =249,
    IK_Play                 =250,
    IK_Zoom                 =251,
    IK_NoName               =252,
    IK_PA1                  =253,
    IK_OEMClear             =254,
    IK_MAX                  =255,
};
enum EInputAction
{
    IST_None                =0,
    IST_Press               =1,
    IST_Hold                =2,
    IST_Release             =3,
    IST_Axis                =4,
    IST_MAX                 =5,
};

class ENGINE_API UInteractions : public UObject
{
public:
    DECLARE_CLASS(UInteractions,UObject,0,Engine)
    NO_DEFAULT_CONSTRUCTOR(UInteractions)
};


struct UInteraction_eventNotifyMusicChange_Parms
{
};
struct UInteraction_eventNotifyLevelChange_Parms
{
};
struct UInteraction_eventInitialized_Parms
{
};
class ENGINE_API UInteraction : public UInteractions
{
public:
    BITFIELD bActive:1 GCC_PACK(4);
    BITFIELD bVisible:1;
    BITFIELD bRequiresTick:1;
    BITFIELD bNativeEvents:1;
    class UPlayer* ViewportOwner GCC_PACK(4);
    class UInteractionMaster* Master;
    DECLARE_FUNCTION(execScreenToWorld);
    DECLARE_FUNCTION(execWorldToScreen);
    DECLARE_FUNCTION(execConsoleCommand);
    DECLARE_FUNCTION(execInitialize);
    void eventNotifyMusicChange()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_NotifyMusicChange),NULL);
    }
    void eventNotifyLevelChange()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_NotifyLevelChange),NULL);
    }
    void eventInitialized()
    {
        ProcessEvent(FindFunctionChecked(ENGINE_Initialized),NULL);
    }
    DECLARE_CLASS(UInteraction,UInteractions,0,Engine)
    NO_DEFAULT_CONSTRUCTOR(UInteraction)
    #include "UInteraction.h"
};


struct UInteractionMaster_eventNotifyLevelChange_Parms
{
    TArray<class UInteraction*> InteractionArray;
};
struct UInteractionMaster_eventProcess_Message_Parms
{
    FString Msg;
    FLOAT MsgLife;
    TArray<class UInteraction*> InteractionArray;
};
struct UInteractionMaster_eventProcess_Tick_Parms
{
    TArray<class UInteraction*> InteractionArray;
    FLOAT DeltaTime;
};
struct UInteractionMaster_eventProcess_PostRender_Parms
{
    TArray<class UInteraction*> InteractionArray;
    class UCanvas* Canvas;
};
struct UInteractionMaster_eventProcess_PreRender_Parms
{
    TArray<class UInteraction*> InteractionArray;
    class UCanvas* Canvas;
};
struct UInteractionMaster_eventProcess_KeyEvent_Parms
{
    TArray<class UInteraction*> InteractionArray;
    BYTE Key;
    BYTE Action;
    FLOAT Delta;
    BITFIELD ReturnValue;
};
struct UInteractionMaster_eventProcess_KeyType_Parms
{
    TArray<class UInteraction*> InteractionArray;
    BYTE Key;
    FString Unicode;
    BITFIELD ReturnValue;
};
struct UInteractionMaster_eventSetFocusTo_Parms
{
    class UInteraction* Inter;
    class UPlayer* ViewportOwner;
};
struct UInteractionMaster_eventRemoveInteraction_Parms
{
    class UInteraction* RemoveMe;
};
struct UInteractionMaster_eventAddInteraction_Parms
{
    FString InteractionName;
    class UPlayer* AttachTo;
    class UInteraction* ReturnValue;
};
class ENGINE_API UInteractionMaster : public UInteractions
{
public:
    class UClient* Client GCC_PACK(4);
    class UInteraction* BaseMenu;
    class UInteraction* Console;
    TArrayNoInit<class UInteraction*> GlobalInteractions;
    BITFIELD bRequireRawJoystick:1 GCC_PACK(4);
    DECLARE_FUNCTION(execTravel);
    void eventNotifyLevelChange(TArray<class UInteraction*> InteractionArray)
    {
        UInteractionMaster_eventNotifyLevelChange_Parms Parms;
        Parms.InteractionArray=InteractionArray;
        ProcessEvent(FindFunctionChecked(ENGINE_NotifyLevelChange),&Parms);
    }
    void eventProcess_Message(const FString& Msg, FLOAT MsgLife, TArray<class UInteraction*> InteractionArray)
    {
        UInteractionMaster_eventProcess_Message_Parms Parms;
        Parms.Msg=Msg;
        Parms.MsgLife=MsgLife;
        Parms.InteractionArray=InteractionArray;
        ProcessEvent(FindFunctionChecked(ENGINE_Process_Message),&Parms);
    }
    void eventProcess_Tick(TArray<class UInteraction*> InteractionArray, FLOAT DeltaTime)
    {
        UInteractionMaster_eventProcess_Tick_Parms Parms;
        Parms.InteractionArray=InteractionArray;
        Parms.DeltaTime=DeltaTime;
        ProcessEvent(FindFunctionChecked(ENGINE_Process_Tick),&Parms);
    }
    void eventProcess_PostRender(TArray<class UInteraction*> InteractionArray, class UCanvas* Canvas)
    {
        UInteractionMaster_eventProcess_PostRender_Parms Parms;
        Parms.InteractionArray=InteractionArray;
        Parms.Canvas=Canvas;
        ProcessEvent(FindFunctionChecked(ENGINE_Process_PostRender),&Parms);
    }
    void eventProcess_PreRender(TArray<class UInteraction*> InteractionArray, class UCanvas* Canvas)
    {
        UInteractionMaster_eventProcess_PreRender_Parms Parms;
        Parms.InteractionArray=InteractionArray;
        Parms.Canvas=Canvas;
        ProcessEvent(FindFunctionChecked(ENGINE_Process_PreRender),&Parms);
    }
    BITFIELD eventProcess_KeyEvent(TArray<class UInteraction*> InteractionArray, BYTE& Key, BYTE& Action, FLOAT Delta)
    {
        UInteractionMaster_eventProcess_KeyEvent_Parms Parms;
        Parms.ReturnValue=0;
        Parms.InteractionArray=InteractionArray;
        Parms.Key=Key;
        Parms.Action=Action;
        Parms.Delta=Delta;
        ProcessEvent(FindFunctionChecked(ENGINE_Process_KeyEvent),&Parms);
        Key=Parms.Key;
        Action=Parms.Action;
        return Parms.ReturnValue;
    }
    BITFIELD eventProcess_KeyType(TArray<class UInteraction*> InteractionArray, BYTE& Key, const FString& Unicode)
    {
        UInteractionMaster_eventProcess_KeyType_Parms Parms;
        Parms.ReturnValue=0;
        Parms.InteractionArray=InteractionArray;
        Parms.Key=Key;
        Parms.Unicode=Unicode;
        ProcessEvent(FindFunctionChecked(ENGINE_Process_KeyType),&Parms);
        Key=Parms.Key;
        return Parms.ReturnValue;
    }
    void eventSetFocusTo(class UInteraction* Inter, class UPlayer* ViewportOwner)
    {
        UInteractionMaster_eventSetFocusTo_Parms Parms;
        Parms.Inter=Inter;
        Parms.ViewportOwner=ViewportOwner;
        ProcessEvent(FindFunctionChecked(ENGINE_SetFocusTo),&Parms);
    }
    void eventRemoveInteraction(class UInteraction* RemoveMe)
    {
        UInteractionMaster_eventRemoveInteraction_Parms Parms;
        Parms.RemoveMe=RemoveMe;
        ProcessEvent(FindFunctionChecked(ENGINE_RemoveInteraction),&Parms);
    }
    class UInteraction* eventAddInteraction(const FString& InteractionName, class UPlayer* AttachTo)
    {
        UInteractionMaster_eventAddInteraction_Parms Parms;
        Parms.ReturnValue=0;
        Parms.InteractionName=InteractionName;
        Parms.AttachTo=AttachTo;
        ProcessEvent(FindFunctionChecked(ENGINE_AddInteraction),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UInteractionMaster,UInteractions,0|CLASS_Transient,Engine)
    NO_DEFAULT_CONSTRUCTOR(UInteractionMaster)
    #include "UInteractionMaster.h"
};

#endif

AUTOGENERATE_FUNCTION(AActor,552,execMultiply_ColorFloat);
AUTOGENERATE_FUNCTION(AActor,551,execAdd_ColorColor);
AUTOGENERATE_FUNCTION(AActor,550,execMultiply_FloatColor);
AUTOGENERATE_FUNCTION(AActor,549,execSubtract_ColorColor);
AUTOGENERATE_FUNCTION(AActor,321,execCollidingActors);
AUTOGENERATE_FUNCTION(AActor,312,execVisibleCollidingActors);
AUTOGENERATE_FUNCTION(AActor,311,execVisibleActors);
AUTOGENERATE_FUNCTION(AActor,310,execRadiusActors);
AUTOGENERATE_FUNCTION(AActor,309,execTraceActors);
AUTOGENERATE_FUNCTION(AActor,307,execTouchingActors);
AUTOGENERATE_FUNCTION(AActor,306,execBasedActors);
AUTOGENERATE_FUNCTION(AActor,305,execChildActors);
AUTOGENERATE_FUNCTION(AActor,313,execDynamicActors);
AUTOGENERATE_FUNCTION(AActor,304,execAllActors);
AUTOGENERATE_FUNCTION(AActor,-1,execMoveCacheEntry);
AUTOGENERATE_FUNCTION(AActor,-1,execGetCacheEntry);
AUTOGENERATE_FUNCTION(AActor,-1,execGetAllIntDesc);
AUTOGENERATE_FUNCTION(AActor,-1,execGetAllInt);
AUTOGENERATE_FUNCTION(AActor,-1,execGetNextIntDesc);
AUTOGENERATE_FUNCTION(AActor,-1,execGetNextInt);
AUTOGENERATE_FUNCTION(AActor,547,execGetURLMap);
AUTOGENERATE_FUNCTION(AActor,545,execGetNextSkin);
AUTOGENERATE_FUNCTION(AActor,539,execGetMapName);
AUTOGENERATE_FUNCTION(AActor,-1,execAddToPackageMap);
AUTOGENERATE_FUNCTION(AActor,-1,execResetStaticFilterState);
AUTOGENERATE_FUNCTION(AActor,-1,execSuggestFallVelocity);
AUTOGENERATE_FUNCTION(AActor,532,execPlayerCanSeeMe);
AUTOGENERATE_FUNCTION(AActor,512,execMakeNoise);
AUTOGENERATE_FUNCTION(AActor,-1,execForceFeedbackSupported);
AUTOGENERATE_FUNCTION(AActor,569,execChangeBaseParamsFeedbackEffect);
AUTOGENERATE_FUNCTION(AActor,568,execChangeSpringFeedbackEffect);
AUTOGENERATE_FUNCTION(AActor,567,execStopFeedbackEffect);
AUTOGENERATE_FUNCTION(AActor,566,execPlayFeedbackEffect);
AUTOGENERATE_FUNCTION(AActor,-1,execGetSoundDuration);
AUTOGENERATE_FUNCTION(AActor,-1,execDemoPlaySound);
AUTOGENERATE_FUNCTION(AActor,-1,execPlayOwnedSound);
AUTOGENERATE_FUNCTION(AActor,264,execPlaySound);
AUTOGENERATE_FUNCTION(AActor,280,execSetTimer);
AUTOGENERATE_FUNCTION(AActor,279,execDestroy);
AUTOGENERATE_FUNCTION(AActor,278,execSpawn);
AUTOGENERATE_FUNCTION(AActor,-1,execTraceThisActor);
AUTOGENERATE_FUNCTION(AActor,548,execFastTrace);
AUTOGENERATE_FUNCTION(AActor,277,execTrace);
AUTOGENERATE_FUNCTION(AActor,-1,execStopAllMusic);
AUTOGENERATE_FUNCTION(AActor,-1,execStopMusic);
AUTOGENERATE_FUNCTION(AActor,-1,execPlayMusic);
AUTOGENERATE_FUNCTION(AActor,-1,execPauseStream);
AUTOGENERATE_FUNCTION(AActor,-1,execAdjustVolume);
AUTOGENERATE_FUNCTION(AActor,-1,execSeekStream);
AUTOGENERATE_FUNCTION(AActor,-1,execStopStream);
AUTOGENERATE_FUNCTION(AActor,-1,execPlayStream);
AUTOGENERATE_FUNCTION(AActor,-1,execAllowMusicPlayback);
AUTOGENERATE_FUNCTION(AActor,-1,execUnClock);
AUTOGENERATE_FUNCTION(AActor,-1,execClock);
AUTOGENERATE_FUNCTION(AActor,-1,execKIsRagdollAvailable);
AUTOGENERATE_FUNCTION(AActor,-1,execKMakeRagdollAvailable);
AUTOGENERATE_FUNCTION(AActor,-1,execKRemoveAllBoneLifters);
AUTOGENERATE_FUNCTION(AActor,-1,execKRemoveLifterFromBone);
AUTOGENERATE_FUNCTION(AActor,-1,execKAddBoneLifter);
AUTOGENERATE_FUNCTION(AActor,-1,execKScaleJointLimits);
AUTOGENERATE_FUNCTION(AActor,-1,execKFreezeRagdoll);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetSkelMass);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetSkelVel);
AUTOGENERATE_FUNCTION(AActor,-1,execKEnableCollision);
AUTOGENERATE_FUNCTION(AActor,-1,execKDisableCollision);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetActorGravScale);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetActorGravScale);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetBlockKarma);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetStayUprightParams);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetStayUpright);
AUTOGENERATE_FUNCTION(AActor,-1,execKAddAngularImpulse);
AUTOGENERATE_FUNCTION(AActor,-1,execKAddImpulse);
AUTOGENERATE_FUNCTION(AActor,-1,execKIsAwake);
AUTOGENERATE_FUNCTION(AActor,-1,execKWake);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetImpactThreshold);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetImpactThreshold);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetCOMPosition);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetCOMOffset);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetCOMOffset);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetRestitution);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetRestitution);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetFriction);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetFriction);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetDampingProps);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetDampingProps);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetInertiaTensor);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetInertiaTensor);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetMass);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetMass);
AUTOGENERATE_FUNCTION(AActor,-1,execKRBVecFromVector);
AUTOGENERATE_FUNCTION(AActor,-1,execKRBVecToVector);
AUTOGENERATE_FUNCTION(AActor,-1,execKDrawRigidBodyState);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetRigidBodyState);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetRBQuaternion);
AUTOGENERATE_FUNCTION(AActor,-1,execKSetSimParams);
AUTOGENERATE_FUNCTION(AActor,-1,execKGetSimParams);
AUTOGENERATE_FUNCTION(AActor,-1,execOnlyAffectPawns);
AUTOGENERATE_FUNCTION(AActor,3970,execSetPhysics);
AUTOGENERATE_FUNCTION(AActor,301,execFinishInterpolation);
AUTOGENERATE_FUNCTION(AActor,-1,execDebugUnclock);
AUTOGENERATE_FUNCTION(AActor,-1,execDebugClock);
AUTOGENERATE_FUNCTION(AActor,-1,execClearStayingDebugLines);
AUTOGENERATE_FUNCTION(AActor,-1,execDrawDebugSphere);
AUTOGENERATE_FUNCTION(AActor,-1,execDrawDebugCircle);
AUTOGENERATE_FUNCTION(AActor,-1,execDrawStayingDebugLine);
AUTOGENERATE_FUNCTION(AActor,-1,execDrawDebugLine);
AUTOGENERATE_FUNCTION(AActor,-1,execGetRenderBoundingSphere);
AUTOGENERATE_FUNCTION(AActor,-1,execGetUrlOption);
AUTOGENERATE_FUNCTION(AActor,-1,execUpdateURL);
AUTOGENERATE_FUNCTION(AActor,-1,execGetClosestBone);
AUTOGENERATE_FUNCTION(AActor,-1,execAnimIsInGroup);
AUTOGENERATE_FUNCTION(AActor,-1,execGetAnimParams);
AUTOGENERATE_FUNCTION(AActor,-1,execSetBoneRotation);
AUTOGENERATE_FUNCTION(AActor,-1,execSetBoneLocation);
AUTOGENERATE_FUNCTION(AActor,-1,execSetBoneDirection);
AUTOGENERATE_FUNCTION(AActor,-1,execSetBoneScale);
AUTOGENERATE_FUNCTION(AActor,-1,execLockRootMotion);
AUTOGENERATE_FUNCTION(AActor,-1,execDetachFromBone);
AUTOGENERATE_FUNCTION(AActor,-1,execAttachToBone);
AUTOGENERATE_FUNCTION(AActor,-1,execGetRootRotationDelta);
AUTOGENERATE_FUNCTION(AActor,-1,execGetRootLocationDelta);
AUTOGENERATE_FUNCTION(AActor,-1,execGetRootRotation);
AUTOGENERATE_FUNCTION(AActor,-1,execGetRootLocation);
AUTOGENERATE_FUNCTION(AActor,-1,execGetBoneRotation);
AUTOGENERATE_FUNCTION(AActor,-1,execGetBoneCoords);
AUTOGENERATE_FUNCTION(AActor,-1,execAnimBlendToAlpha);
AUTOGENERATE_FUNCTION(AActor,-1,execAnimBlendParams);
AUTOGENERATE_FUNCTION(AActor,-1,execBoneRefresh);
AUTOGENERATE_FUNCTION(AActor,-1,execLinkMesh);
AUTOGENERATE_FUNCTION(AActor,-1,execLinkSkelAnim);
AUTOGENERATE_FUNCTION(AActor,-1,execGetNotifyChannel);
AUTOGENERATE_FUNCTION(AActor,-1,execEnableChannelNotify);
AUTOGENERATE_FUNCTION(AActor,-1,execCurrentLIPSincAnim);
AUTOGENERATE_FUNCTION(AActor,-1,execIsPlayingLIPSincAnim);
AUTOGENERATE_FUNCTION(AActor,-1,execHasLIPSincAnim);
AUTOGENERATE_FUNCTION(AActor,-1,execStopLIPSincAnim);
AUTOGENERATE_FUNCTION(AActor,-1,execPlayLIPSincAnim);
AUTOGENERATE_FUNCTION(AActor,-1,execAnimStopLooping);
AUTOGENERATE_FUNCTION(AActor,-1,execIsTweening);
AUTOGENERATE_FUNCTION(AActor,-1,execSetAnimFrame);
AUTOGENERATE_FUNCTION(AActor,-1,execFreezeAnimAt);
AUTOGENERATE_FUNCTION(AActor,-1,execStopAnimating);
AUTOGENERATE_FUNCTION(AActor,263,execHasAnim);
AUTOGENERATE_FUNCTION(AActor,261,execFinishAnim);
AUTOGENERATE_FUNCTION(AActor,282,execIsAnimating);
AUTOGENERATE_FUNCTION(AActor,294,execTweenAnim);
AUTOGENERATE_FUNCTION(AActor,260,execLoopAnim);
AUTOGENERATE_FUNCTION(AActor,259,execPlayAnim);
AUTOGENERATE_FUNCTION(AActor,-1,execGetMeshName);
AUTOGENERATE_FUNCTION(AActor,-1,execIsJoinedTo);
AUTOGENERATE_FUNCTION(AActor,272,execSetOwner);
AUTOGENERATE_FUNCTION(AActor,298,execSetBase);
AUTOGENERATE_FUNCTION(AActor,3971,execAutonomousPhysics);
AUTOGENERATE_FUNCTION(AActor,3969,execMoveSmooth);
AUTOGENERATE_FUNCTION(AActor,-1,execSetRelativeLocation);
AUTOGENERATE_FUNCTION(AActor,-1,execSetRelativeRotation);
AUTOGENERATE_FUNCTION(AActor,299,execSetRotation);
AUTOGENERATE_FUNCTION(AActor,267,execSetLocation);
AUTOGENERATE_FUNCTION(AActor,266,execMove);
AUTOGENERATE_FUNCTION(AActor,-1,execSetDrawType);
AUTOGENERATE_FUNCTION(AActor,-1,execSetStaticMesh);
AUTOGENERATE_FUNCTION(AActor,-1,execSetDrawScale3D);
AUTOGENERATE_FUNCTION(AActor,-1,execSetDrawScale);
AUTOGENERATE_FUNCTION(AActor,283,execSetCollisionSize);
AUTOGENERATE_FUNCTION(AActor,262,execSetCollision);
AUTOGENERATE_FUNCTION(AActor,256,execSleep);
AUTOGENERATE_FUNCTION(AActor,-1,execShouldBeHidden);
AUTOGENERATE_FUNCTION(AActor,233,execError);
AUTOGENERATE_FUNCTION(AActor,-1,execTextToSpeech);
AUTOGENERATE_FUNCTION(AActor,-1,execCopyObjectToClipboard);
AUTOGENERATE_FUNCTION(AActor,-1,execConsoleCommand);
AUTOGENERATE_FUNCTION(UInteraction,-1,execScreenToWorld);
AUTOGENERATE_FUNCTION(UInteraction,-1,execWorldToScreen);
AUTOGENERATE_FUNCTION(UInteraction,-1,execConsoleCommand);
AUTOGENERATE_FUNCTION(UInteraction,-1,execInitialize);
AUTOGENERATE_FUNCTION(UInteractionMaster,-1,execTravel);
AUTOGENERATE_FUNCTION(ASecurity,-1,execLocalPerform);
AUTOGENERATE_FUNCTION(ASecurity,-1,execNativePerform);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif


#ifdef NATIVE_DEFS_ONLY
DECLARE_NATIVE_TYPE(Engine,AActor);
DECLARE_NATIVE_TYPE(Engine,AInfo);
DECLARE_NATIVE_TYPE(Engine,UInteraction);
DECLARE_NATIVE_TYPE(Engine,UInteractions);
DECLARE_NATIVE_TYPE(Engine,UInteractionMaster);
DECLARE_NATIVE_TYPE(Engine,AMutator);
DECLARE_NATIVE_TYPE(Engine,ASecurity);

#define AUTO_INITIALIZE_REGISTRANTS_ENGINE \
	AActor::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindEngineAActorNative; \
	AInfo::StaticClass(); \
	UInteraction::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindEngineUInteractionNative; \
	UInteractions::StaticClass(); \
	UInteractionMaster::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindEngineUInteractionMasterNative; \
	AMutator::StaticClass(); \
	ASecurity::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindEngineASecurityNative; \

#endif // NATIVE_DEFS_ONLY

#ifdef NATIVES_ONLY
NATIVE_INFO(AActor) GEngineAActorNatives[] = 
{ 
	MAP_NATIVE(AActor,execMultiply_ColorFloat)
	MAP_NATIVE(AActor,execAdd_ColorColor)
	MAP_NATIVE(AActor,execMultiply_FloatColor)
	MAP_NATIVE(AActor,execSubtract_ColorColor)
	MAP_NATIVE(AActor,execCollidingActors)
	MAP_NATIVE(AActor,execVisibleCollidingActors)
	MAP_NATIVE(AActor,execVisibleActors)
	MAP_NATIVE(AActor,execRadiusActors)
	MAP_NATIVE(AActor,execTraceActors)
	MAP_NATIVE(AActor,execTouchingActors)
	MAP_NATIVE(AActor,execBasedActors)
	MAP_NATIVE(AActor,execChildActors)
	MAP_NATIVE(AActor,execDynamicActors)
	MAP_NATIVE(AActor,execAllActors)
	MAP_NATIVE(AActor,execMoveCacheEntry)
	MAP_NATIVE(AActor,execGetCacheEntry)
	MAP_NATIVE(AActor,execGetAllIntDesc)
	MAP_NATIVE(AActor,execGetAllInt)
	MAP_NATIVE(AActor,execGetNextIntDesc)
	MAP_NATIVE(AActor,execGetNextInt)
	MAP_NATIVE(AActor,execGetURLMap)
	MAP_NATIVE(AActor,execGetNextSkin)
	MAP_NATIVE(AActor,execGetMapName)
	MAP_NATIVE(AActor,execAddToPackageMap)
	MAP_NATIVE(AActor,execResetStaticFilterState)
	MAP_NATIVE(AActor,execSuggestFallVelocity)
	MAP_NATIVE(AActor,execPlayerCanSeeMe)
	MAP_NATIVE(AActor,execMakeNoise)
	MAP_NATIVE(AActor,execForceFeedbackSupported)
	MAP_NATIVE(AActor,execChangeBaseParamsFeedbackEffect)
	MAP_NATIVE(AActor,execChangeSpringFeedbackEffect)
	MAP_NATIVE(AActor,execStopFeedbackEffect)
	MAP_NATIVE(AActor,execPlayFeedbackEffect)
	MAP_NATIVE(AActor,execGetSoundDuration)
	MAP_NATIVE(AActor,execDemoPlaySound)
	MAP_NATIVE(AActor,execPlayOwnedSound)
	MAP_NATIVE(AActor,execPlaySound)
	MAP_NATIVE(AActor,execSetTimer)
	MAP_NATIVE(AActor,execDestroy)
	MAP_NATIVE(AActor,execSpawn)
	MAP_NATIVE(AActor,execTraceThisActor)
	MAP_NATIVE(AActor,execFastTrace)
	MAP_NATIVE(AActor,execTrace)
	MAP_NATIVE(AActor,execStopAllMusic)
	MAP_NATIVE(AActor,execStopMusic)
	MAP_NATIVE(AActor,execPlayMusic)
	MAP_NATIVE(AActor,execPauseStream)
	MAP_NATIVE(AActor,execAdjustVolume)
	MAP_NATIVE(AActor,execSeekStream)
	MAP_NATIVE(AActor,execStopStream)
	MAP_NATIVE(AActor,execPlayStream)
	MAP_NATIVE(AActor,execAllowMusicPlayback)
	MAP_NATIVE(AActor,execUnClock)
	MAP_NATIVE(AActor,execClock)
	MAP_NATIVE(AActor,execKIsRagdollAvailable)
	MAP_NATIVE(AActor,execKMakeRagdollAvailable)
	MAP_NATIVE(AActor,execKRemoveAllBoneLifters)
	MAP_NATIVE(AActor,execKRemoveLifterFromBone)
	MAP_NATIVE(AActor,execKAddBoneLifter)
	MAP_NATIVE(AActor,execKScaleJointLimits)
	MAP_NATIVE(AActor,execKFreezeRagdoll)
	MAP_NATIVE(AActor,execKGetSkelMass)
	MAP_NATIVE(AActor,execKSetSkelVel)
	MAP_NATIVE(AActor,execKEnableCollision)
	MAP_NATIVE(AActor,execKDisableCollision)
	MAP_NATIVE(AActor,execKGetActorGravScale)
	MAP_NATIVE(AActor,execKSetActorGravScale)
	MAP_NATIVE(AActor,execKSetBlockKarma)
	MAP_NATIVE(AActor,execKSetStayUprightParams)
	MAP_NATIVE(AActor,execKSetStayUpright)
	MAP_NATIVE(AActor,execKAddAngularImpulse)
	MAP_NATIVE(AActor,execKAddImpulse)
	MAP_NATIVE(AActor,execKIsAwake)
	MAP_NATIVE(AActor,execKWake)
	MAP_NATIVE(AActor,execKGetImpactThreshold)
	MAP_NATIVE(AActor,execKSetImpactThreshold)
	MAP_NATIVE(AActor,execKGetCOMPosition)
	MAP_NATIVE(AActor,execKGetCOMOffset)
	MAP_NATIVE(AActor,execKSetCOMOffset)
	MAP_NATIVE(AActor,execKGetRestitution)
	MAP_NATIVE(AActor,execKSetRestitution)
	MAP_NATIVE(AActor,execKGetFriction)
	MAP_NATIVE(AActor,execKSetFriction)
	MAP_NATIVE(AActor,execKGetDampingProps)
	MAP_NATIVE(AActor,execKSetDampingProps)
	MAP_NATIVE(AActor,execKGetInertiaTensor)
	MAP_NATIVE(AActor,execKSetInertiaTensor)
	MAP_NATIVE(AActor,execKGetMass)
	MAP_NATIVE(AActor,execKSetMass)
	MAP_NATIVE(AActor,execKRBVecFromVector)
	MAP_NATIVE(AActor,execKRBVecToVector)
	MAP_NATIVE(AActor,execKDrawRigidBodyState)
	MAP_NATIVE(AActor,execKGetRigidBodyState)
	MAP_NATIVE(AActor,execKGetRBQuaternion)
	MAP_NATIVE(AActor,execKSetSimParams)
	MAP_NATIVE(AActor,execKGetSimParams)
	MAP_NATIVE(AActor,execOnlyAffectPawns)
	MAP_NATIVE(AActor,execSetPhysics)
	MAP_NATIVE(AActor,execFinishInterpolation)
	MAP_NATIVE(AActor,execDebugUnclock)
	MAP_NATIVE(AActor,execDebugClock)
	MAP_NATIVE(AActor,execClearStayingDebugLines)
	MAP_NATIVE(AActor,execDrawDebugSphere)
	MAP_NATIVE(AActor,execDrawDebugCircle)
	MAP_NATIVE(AActor,execDrawStayingDebugLine)
	MAP_NATIVE(AActor,execDrawDebugLine)
	MAP_NATIVE(AActor,execGetRenderBoundingSphere)
	MAP_NATIVE(AActor,execGetUrlOption)
	MAP_NATIVE(AActor,execUpdateURL)
	MAP_NATIVE(AActor,execGetClosestBone)
	MAP_NATIVE(AActor,execAnimIsInGroup)
	MAP_NATIVE(AActor,execGetAnimParams)
	MAP_NATIVE(AActor,execSetBoneRotation)
	MAP_NATIVE(AActor,execSetBoneLocation)
	MAP_NATIVE(AActor,execSetBoneDirection)
	MAP_NATIVE(AActor,execSetBoneScale)
	MAP_NATIVE(AActor,execLockRootMotion)
	MAP_NATIVE(AActor,execDetachFromBone)
	MAP_NATIVE(AActor,execAttachToBone)
	MAP_NATIVE(AActor,execGetRootRotationDelta)
	MAP_NATIVE(AActor,execGetRootLocationDelta)
	MAP_NATIVE(AActor,execGetRootRotation)
	MAP_NATIVE(AActor,execGetRootLocation)
	MAP_NATIVE(AActor,execGetBoneRotation)
	MAP_NATIVE(AActor,execGetBoneCoords)
	MAP_NATIVE(AActor,execAnimBlendToAlpha)
	MAP_NATIVE(AActor,execAnimBlendParams)
	MAP_NATIVE(AActor,execBoneRefresh)
	MAP_NATIVE(AActor,execLinkMesh)
	MAP_NATIVE(AActor,execLinkSkelAnim)
	MAP_NATIVE(AActor,execGetNotifyChannel)
	MAP_NATIVE(AActor,execEnableChannelNotify)
	MAP_NATIVE(AActor,execCurrentLIPSincAnim)
	MAP_NATIVE(AActor,execIsPlayingLIPSincAnim)
	MAP_NATIVE(AActor,execHasLIPSincAnim)
	MAP_NATIVE(AActor,execStopLIPSincAnim)
	MAP_NATIVE(AActor,execPlayLIPSincAnim)
	MAP_NATIVE(AActor,execAnimStopLooping)
	MAP_NATIVE(AActor,execIsTweening)
	MAP_NATIVE(AActor,execSetAnimFrame)
	MAP_NATIVE(AActor,execFreezeAnimAt)
	MAP_NATIVE(AActor,execStopAnimating)
	MAP_NATIVE(AActor,execHasAnim)
	MAP_NATIVE(AActor,execFinishAnim)
	MAP_NATIVE(AActor,execIsAnimating)
	MAP_NATIVE(AActor,execTweenAnim)
	MAP_NATIVE(AActor,execLoopAnim)
	MAP_NATIVE(AActor,execPlayAnim)
	MAP_NATIVE(AActor,execGetMeshName)
	MAP_NATIVE(AActor,execIsJoinedTo)
	MAP_NATIVE(AActor,execSetOwner)
	MAP_NATIVE(AActor,execSetBase)
	MAP_NATIVE(AActor,execAutonomousPhysics)
	MAP_NATIVE(AActor,execMoveSmooth)
	MAP_NATIVE(AActor,execSetRelativeLocation)
	MAP_NATIVE(AActor,execSetRelativeRotation)
	MAP_NATIVE(AActor,execSetRotation)
	MAP_NATIVE(AActor,execSetLocation)
	MAP_NATIVE(AActor,execMove)
	MAP_NATIVE(AActor,execSetDrawType)
	MAP_NATIVE(AActor,execSetStaticMesh)
	MAP_NATIVE(AActor,execSetDrawScale3D)
	MAP_NATIVE(AActor,execSetDrawScale)
	MAP_NATIVE(AActor,execSetCollisionSize)
	MAP_NATIVE(AActor,execSetCollision)
	MAP_NATIVE(AActor,execSleep)
	MAP_NATIVE(AActor,execShouldBeHidden)
	MAP_NATIVE(AActor,execError)
	MAP_NATIVE(AActor,execTextToSpeech)
	MAP_NATIVE(AActor,execCopyObjectToClipboard)
	MAP_NATIVE(AActor,execConsoleCommand)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Engine,AActor);

NATIVE_INFO(UInteraction) GEngineUInteractionNatives[] = 
{ 
	MAP_NATIVE(UInteraction,execScreenToWorld)
	MAP_NATIVE(UInteraction,execWorldToScreen)
	MAP_NATIVE(UInteraction,execConsoleCommand)
	MAP_NATIVE(UInteraction,execInitialize)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Engine,UInteraction);

NATIVE_INFO(UInteractionMaster) GEngineUInteractionMasterNatives[] = 
{ 
	MAP_NATIVE(UInteractionMaster,execTravel)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Engine,UInteractionMaster);

NATIVE_INFO(ASecurity) GEngineASecurityNatives[] = 
{ 
	MAP_NATIVE(ASecurity,execLocalPerform)
	MAP_NATIVE(ASecurity,execNativePerform)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Engine,ASecurity);

#endif // NATIVES_ONLY

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(AActor)
VERIFY_CLASS_SIZE_NODIE(AInfo)
VERIFY_CLASS_SIZE_NODIE(UInteraction)
VERIFY_CLASS_SIZE_NODIE(UInteractions)
VERIFY_CLASS_SIZE_NODIE(UInteractionMaster)
VERIFY_CLASS_SIZE_NODIE(AMutator)
VERIFY_CLASS_SIZE_NODIE(ASecurity)
#endif // VERIFY_CLASS_SIZES
